version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: selelab-admin-api
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql-confd:/etc/mysql/conf.d
networks:
  default:
    external:
      name: db_sharing
