version: '3'
services:
  redis:
    image: redis
    volumes:
      - "./data/redis:/data"
    restart: always
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: default-db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql-confd:/etc/mysql/conf.d
    restart: always
networks:
  default:
    external:
      name: db_sharing
